### ISSUE TITLE
Support UnifiedPush

### ISSUE THREAD

**Issue by genofire** [threema-ch/push-relay#44]
On Android, there exists also an Push Notification Service called:
[UnifiedPush](https://unifiedpush.org/)

On this way, user could manage his own Notification Server for more privacy without battery drain pooling

**Comment by paul70011** [comment]
I would also like to see this getting added. Messages arrive too late with polling and receiving calls is very unreliable.

**Comment by genofire** [comment]
Sadly Threema has implement his own Push Notification (and drop pulling for it).
That drains my battery a lot ;(

**Comment by genofire** [comment]
Drains means that it cost me more battery then ntfy.sh and Conversations (we also holds a constant connection).
That are just a few percent (against apps u use long time in foreground).

I do not allow to run signal in background, also because of battery usage.

**Comment by threema-lenny** [comment]
I'll close this issue as we will not implemented UnifiedPush for Threema Web because Threema Web is being replaced with Desktop 2.0, putting this project out of work soon.

If what you actually wanted is UnifiedPush for Threema itself, then that would need to be implemented in the Threema Chat Server instead. However, Threema Push (i.e. the glorified TCP connection) works very well in practice and, as mentioned, the battery drain is insignificant, so it's not planned to integrate UnifiedPush. But you'll never know.

**Comment by turbocool3r** [comment]
I use Threema for communication with clients and at my previous workplace we used Threema Work, so timely push notifications are important for my use case. Threema Push generally works, but the problems start when I have to use a VPN (in UAE, for example, Threema calls do not work without a VPN): since VPN connection isn't always stable notifications break quite often. For other apps like Telegram or Element the solution is to whitelist the UnifiedPush app in VPN settings so you don't have to always remember to turn VPN on or off.
